spring:
  jackson.serialization.WRITE_DATES_AS_TIMESTAMPS: false

jpa:
#    show-sql: true
#    properties.hibernate.format_sql: true

logging:
  level:
    ROOT: INFO
    org:
      hopto.eriksen: DEBUG
      hibernate: ERROR
      springframework: INFO
  pattern:
    console: "%-5level [%-13.13thread] %-45.45logger{44} :  %m%n"

