eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: ssh-log-watcher

logging:
  level:
    ROOT: INFO
    org:
      hopto.eriksen: DEBUG
      springframework: INFO
  pattern:
    console: "%-5level [%-13.13thread] %-45.45logger{44} :  %m%n"